[package]
name = "keystone_gauntlet_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "keystone_gauntlet_rust"
path = "src/main.rs"

[dependencies]
serde_jcs = "0.2.0"
serde_json = "1"
sha2 = "0.10"

[[bin]]
name = "gc"
path = "src/gc_main.rs"

[[bin]]
name = "sr"
path = "src/sr_main.rs"

[[bin]]
name = "tg"
path = "src/tg_main.rs"

[[bin]]
name = "rev"
path = "src/rev_main.rs"
